spring:
  datasource:
    rcm-rdb:
      promotion:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://DB_ADDRESS:DB_PORT/mc_promotion?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull
        password: 
        url: jdbc:mysql://DB_ADDRESS:DB_PORT/mc_promotion?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull
        username: 
        hibernate:
          cache:
            use_query_cache: true
            use_second_level_cache: true
            redisson:
              entity-offer:
                eviction:
                  max_entries: 100000
                expiration:
                  time_to_live: 86400000
              query-offer:
                eviction:
                  max_entries: 100000
                expiration:
                  time_to_live: 86400000
              entity-dynamicPrice:
                eviction:
                  max_entries: 100000
                expiration:
                  time_to_live: 86400000
              query-dynamicPrice:
                eviction:
                  max_entries: 100000
                expiration:
                  time_to_live: 86400000
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          hbm2ddl:
            auto: update
          show_sql: true
    rcm-mongo: # for override spring.data.mongodb.* values each at services
      promotion:
        connectionString: mongodb+srv://MONGO_CLIENT_ID:MONGO_CLIENT_PASSWORD@MONGODB_ADDRESS/rcm-promotion?retryWrites=true&w=majority&connecttimeoutms=10000&sockettimeoutms=15000&waitqueuetimeoutms=3000&maxlifetimems=60000&maxlifetimems=120000&heartbeatfrequencyms=20000&ssl=true
        database: rcm-promotion
        username: 
        password: 
        retryWrite: true
        authSource: admin
  application:
    name: "micro-commerce-promotion"
  messages:
    basename: messages/promotion/messages,messages/cloud-common/messages,messages/common/messages

platform:
  config:
    microservice:
      catalog: true

eureka:
  instance:
    intance-id: micro-commerce-promotion-intance
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"